-- =====================================================
-- Fix password hashes for test users
-- The previous hash was invalid for 'password123'
-- 
-- IMPORTANT: BCrypt hashes found online are often incorrect.
-- This hash was generated by Spring's BCryptPasswordEncoder
-- and verified to work with 'password123'
-- =====================================================

-- Verified working BCrypt hash for 'password123'
-- Generated by Spring Boot application using BCryptPasswordEncoder
UPDATE users 
SET password = '$2a$10$xDadE6QLIi0q31uUEGcES.tuU17qpyY5Kv24.q51fRUUiHAwcQOOu'
WHERE username IN ('admin', 'john_doe', 'jane_smith', 'mike_wilson');
